
name: Build and upload conda package

on:
  release:
    types: ['released']

jobs:
  conda_deployment_with_new_tag:
    name: Conda deployment of package with Python ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ["3.9"]
        os: [ubuntu-latest, macos-latest]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Conda environment creation and activation
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: ${{ matrix.python-version }}
          environment-file: devtools/conda-envs/build_env.yaml    # Path to the build conda environment
          miniconda-version: latest
          auto-update-conda: false
          auto-activate-base: false
          show-channel-urls: true
      - name: Set Platforms
        id: set_platforms
        run: |
          if [[ "${{ matrix.os }}" == "ubuntu-latest" ]]; then
            echo "::set-output name=platform_linux-64::true"
            echo "::set-output name=platform_osx-arm64::false"
          elif [[ "${{ matrix.os }}" == "macos-latest" ]]; then
            echo "::set-output name=platform_linux-64::false"
            echo "::set-output name=platform_osx-arm64::true"
          fi
      - name: Build and upload the conda packages
        uses: uibcdf/action-build-and-upload-conda-packages@v1.3.0
        with:
          meta_yaml_dir: devtools/conda-build
          python-version: ${{ matrix.python-version }}
          platform_linux-64: ${{ steps.set_platforms.outputs.platform_linux-64 }}
          platform_osx-arm64: ${{ steps.set_platforms.outputs.platform_osx-arm64 }}
          user: statphysbio
          label: auto
          token: ${{ secrets.ANACONDA_TOKEN }}