name: Build from source and run tests

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'

    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH

    - name: Install Zernikegrams
      run: |
        conda install -y python=3.10 zlib=1.2.13 libzlib=1.2.13
        conda update conda
        conda install -y conda-build
        conda build devtools/conda-build --no-test --output-folder ./build -c conda-forge -c bioconda
        conda install zernikegrams -c ./build -c conda-forge -c bioconda

    - name: reinstall h5py
      run: |
        echo "uninstalling and reinstalling h5py to avoid GH actions issues"
        pip uninstall h5py -y
        pip install h5py

    - name: Install modern gcc
      run: |
        echo "Installing new GNU runtime so that openmm can find GLIBCXX_3.4.30"
        conda install libstdcxx-ng -c conda-forge
    
    - name: Test with pytest
      run: |
        conda install pytest
        pytest
